sudo: required
dist: trusty
language: java
jdk: oraclejdk8
services:
  - docker
cache:
  directories:
    - "$HOME/.m2"
before_script:
  - ./.travis.sh before_script
script:
  - ./.travis.sh script
after_script:
  - ./.travis.sh after_script
env:
  matrix:
    - RIAK_FLAVOR=riak-ts RIAK_DOWNLOAD_URL=docker
    - RIAK_VERSION=2.0.7 RIAK_FLAVOR=riak-kv RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.7/ubuntu/trusty/riak_2.0.7-1_amd64.deb
    - RIAK_VERSION=2.1.4 RIAK_FLAVOR=riak-kv RIAK_DOWNLOAD_URL=http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.4/ubuntu/trusty/riak_2.1.4-1_amd64.deb
  global:
    - RIAK_HOSTS=localhost:8087
notifications:
  slack:
    secure: lCGUVnffHyrS1rpOlencvFdID7pVF2leOvbmxAKf/svkjJDLd0BWa9SgLjUDtAQ7vCa8B03rO0fWmlyynDJBQmudjytm+h8BVgAFJNm0SQOAm4ALNsWmixo4XoXhPl3rl3VmXRrx/bvLI8nA4ZIARak6RXoOXqHnl8KmkNhhxw8=
